#!/bin/bash

# Extract and format data using jq, awk, and sed
jq -r '
  .name + " " + (.height/10|tostring) + " " + (.weight/10|tostring) + " " + .types[0].type.name
' data.json | 
awk '{
  # Capitalize first letter of type
  type = $4
  sub(/^./, toupper(substr(type,1,1)), type)
  
  # Format the output exactly as required
  printf "%s is of type %s, weighs %dkg, and is %.1fm tall.\n", $1, type, $3, $2
}'